mode2f <- tibble("mode_prime" = c("Transit excluding GO rail",
                                  "Auto driver",
                                  "Auto passenger",
                                  "Walk",
                                  "Cycle",
                                  "GO rail only",
                                  "Joint GO rail and local transit",
                                  "Motorcycle",
                                  "Taxi passenger",
                                  "Other",
                                  "School bus",
                                  "Unknown",
                                  "Paid rideshare"),
                 "mode_sec" = c("Transit",
                                "Driver",
                                "Passenger",
                                "Active",
                                "Active",
                                "Transit",
                                "Transit",
                                "Driver",
                                "Passenger",
                                "Other",
                                "Passenger",
                                "Other",
                                "Passenger"))
